#!/bin/sh

#Uncomment this for Vivado 2017.3
VIVADO_VERSION=2018.2
VIVADO_SETUP=Xilinx_Vivado_SDK_2018.2_0614_1954.tar.gz

#Desired image name
IMAGE_NAME=vivado_sds_${VIVADO_VERSION}

#FIXME: figure this out automatically
DOCKERHOST_IP=172.17.0.1



#The following two variables are used by the run.sh-script.

#Directory to mount into /project inside of the container
PROJECTDIR=$PWD/..

#The name of the created container
CONTAINER=vivado_${VIVADO_VERSION}_sds_build
